language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=""  WITH_COVERAGE=1 # environment to test with the latest version of NumPy
  - NUMPY_VERSION="=1.8"
  - NUMPY_VERSION="=1.7"
install:
  - source activate env_name
  - pip install -e '.[all]'
script:
  - flake8 psat/*.py psat/permutation/*.py pstats/permutation/tests/*.py bin/*.py setup.py
  # we just check coverage in the latest version of NumPy
  - if [ ${WITH_COVERAGE} ]; then nosetests emperor --with-coverage --cover-package=emperor --cover-inclusive tests; fi
after_success:
  - coveralls