language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=""  WITH_COVERAGE=1 # environment to test with the latest version of NumPy
  - NUMPY_VERSION="=1.8"
  - NUMPY_VERSION="=1.7"
install:
  - source activate env_name
  - pip install flake8
script:
  - flake8 psat/*.py psat/permutation/*.py psat/permutation/tests/*.py setup.py
after_success:
  - coveralls